version: "3.8"
services:
  myjenkins_with_plugin:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8087:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
  # ssh-agent:
  #   image: jenkins/ssh-agent
volumes:
  jenkins_home:
      